### ISSUE TITLE
addressing inserting multiple docs at once

### ISSUE THREAD

**Issue by guyspy** [hsinyichiu102/vertx-Coroutine-kotlin#2]
https://github.com/hsinyichiu102/vertx-Coroutine-kotlin/blob/master/coroutines/src/main/kotlin/movierating/App.kt#L62-L74

See if there's an `insertMany()` function exposed by mongoClient instance :)

(No need to fix that)

**Comment by hsinyichiu102** [comment]
I think the Library that I used is not the correct one. 
Therefore, there were only insert() or insertWithOptins() that I can use.
I will try to find others and try it later.
Thank you a lot :)

**Comment by guyspy** [comment]
OK 
No need to spend too much time.
Vert.x' mongo db client wrapper actually lacks a lot of cool features comparing with the native mongodb java reactive stream driver. We don't use vertx' mongo in production anyway. Use the native driver directly :)
But it takes some time to integrate and is out of the scope of current assignment. You really don't have to look into it
