### ISSUE TITLE
[request change] Not using coroutine at all

### ISSUE THREAD

**Issue by guyspy** [hsinyichiu102/vertx-Coroutine-kotlin#3]
Hi, your current codes does not utilize coroutine features at all. Please fix this.

Please compare your code:
https://github.com/hsinyichiu102/vertx-Coroutine-kotlin/blob/master/coroutines/src/main/kotlin/movierating/App.kt#L149

with the example:
https://github.com/vert-x3/vertx-examples/blob/4.x/kotlin-examples/coroutines/src/main/kotlin/movierating/App.kt#L66

to see the difference.

We need you to eliminate the callback-style syntax using coroutine.
Please fix this.

**Comment by hsinyichiu102** [comment]
Not sure if it is right at this time.
 I've updated the code based on the original one in JDBC
taking one as example as below:
```
  suspend fun getMovie(ctx: RoutingContext) {
      val movie_id = ctx.pathParam("movie_id")

      val query = JsonObject().put("movie_id", movie_id)
      val result = client.find("movie", query).await()
      if(result.contains(movie_id)){
          ctx.response().end(json {
              obj("movie_id" to movie_id,
                      "title" to result.get(0).getString("title")).encode()
          })
      }else{
          ctx.response().setStatusCode(404).end()
      }
    }
```
Thank you for your comment.

**Comment by guyspy** [comment]
perfect

**Comment by guyspy** [comment]
FYI https://vertx.io/docs/vertx-lang-kotlin-coroutines/kotlin/#_awaiting_the_completion_of_vert_x_asynchronous_results
