### ISSUE TITLE
[request change] PUT methods means update if exist

### ISSUE THREAD

**Issue by guyspy** [hsinyichiu102/vertx-Coroutine-kotlin#5]
Please refer to RESTFul api convention doc: https://restfulapi.net/rest-put-vs-post/

> If the Request-URI refers to an already existing resource – an update operation will happen, otherwise create operation should happen

Your code is not following this convention
https://github.com/hsinyichiu102/vertx-Coroutine-kotlin/blob/master/coroutines/src/main/kotlin/movierating/App.kt#L83

Please fix.

Please refer to https://github.com/hsinyichiu102/vertx-Coroutine-kotlin/issues/4 for more hints

**Comment by hsinyichiu102** [comment]
Sorry for that, I've revised the "insert()" to "findOneAndUpdate()"

```
 /**
   * putMovie: to update a new movie into the movie collection
   */
  suspend fun putMovie(ctx: RoutingContext) {

      val movie_id = ctx.pathParam("movie_id") //
      val query = JsonObject().put("movie_id", movie_id)
      val update= json{
      obj(
              "movie_id" to movie_id,
              "title" to ctx.queryParam("title")[0],
              "rating" to ctx.queryParam("rating")[0]

      )}
      
      val result= client.findOneAndUpdate("movie", query, update).await()
      if(result.containsKey(movie_id)){
          ctx.response().setStatusCode(200).end()
      }
      else{
          ctx.response().setStatusCode(404).end()
      }

  }
```

**Comment by guyspy** [comment]
this is good
And if you're still interested in this issue, please look into the keyword `upsert` when googling mongo's findOneAndUpdate command

**Comment by guyspy** [comment]
BTW, we'd like to invite you to join the team :) . This is an unofficial announcement. Please wait for contact from our HR.

**Comment by hsinyichiu102** [comment]
got it, thank you :)
