### ISSUE TITLE
redundant codes when sending response

### ISSUE THREAD

**Issue by guyspy** [hsinyichiu102/vertx-Coroutine-kotlin#6]
Please compare the original example
https://github.com/vert-x3/vertx-examples/blob/4.x/kotlin-examples/coroutines/src/main/kotlin/movierating/App.kt#L68-L70

with your codes
https://github.com/hsinyichiu102/vertx-Coroutine-kotlin/blob/master/coroutines/src/main/kotlin/movierating/App.kt#L148-L166

The original example has a better and more elegant way of dealing json object using kotlin syntax sugars.
In addition, the content type header will be automatically set by vert.x if it detects the response type is JsonObject. Theres no need to set it here.

**Comment by hsinyichiu102** [comment]
understood. have revised back to the original code.

**Comment by guyspy** [comment]
nicely done
